global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: 
        - host.docker.internal:10135
  - job_name: 'airflow'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - host.docker.internal:10137
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - host.docker.internal:9187
    # params:
    #   auth_module: [foo]
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__
    #     replacement: postgres-exporter:9187
  - job_name: node
    scrape_interval: 10s
    static_configs:
      - targets: 
        - host.docker.internal:10130



