apiVersion: 1
datasources:
  - name: postgresql_db
    type: postgres
    url: host.docker.internal:10131
    user: admin
    secureJsonData:
      password: 'password'
    jsonData:
      database: vacancy
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:10135
    jsonData:
      httpMethod: POST
      manageAlerts: true
      #
#      prometheusType: Prometheus
#      prometheusVersion: 2.44.0
#      cacheLevel: 'High'
#      disableRecordingRules: false
#      incrementalQueryOverlapWindow: 10m
#      exemplarTraceIdDestinations:
#        - datasourceUid: my_jaeger_uid
#          name: traceID
#        - name: traceID
#          url: 'http://localhost:10124/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22${__value.raw}%22%7D%5D'
